### ISSUE TITLE
K8S 환경에서 Kong 설치하기! (API Gateway)

### ISSUE THREAD

**Issue by jisunlim** [jisunlim/bibi-blog#18]
> https://artifacthub.io/packages/helm/kong/kong 2.33.1 version

# 1. 개요
Kong 공식문서에서 여러가지 설치 방법을 안내하고 있는데, 저는 그 중 Helm을 사용하여 설치하였습니다.
가이드를 그대로 설치하지는 않았고, 내부 환경에 맞춰 일부 커스터마이징하였습니다.
https://docs.konghq.com/gateway/latest/install/kubernetes/helm-quickstart/

`Kong for Kubernetes`는 아래와 같이 크게 세 가지로 구성되어 있습니다.
- GUI를 제공하는 `Kong Manager`와 백엔드 API인 `Admin API`를 사용하여 정책 설정
- Gateway 역할을 하는 `Kong Proxy`로 API를 전송하면 정책에 따라 각 API 서버로 전송
![image](https://github.com/jisunlim/bibi-blog/assets/18459083/449d511c-7512-40d9-b174-4c6edcc73fe5)

# 2. 설치
`helm pull kong/kong` 명령어를 사용하여 Helm Chart를 다운로드받은 후 커스터마이징하였습니다.
변경한 항목은 아래와 같습니다. 😄
- 내부 Container Registry 사용 (외부 Repo 사용 불가)
- 미리 설치한 Ingress Controller 사용
- 미리 설치한 NFS provisioner 사용
- (임시) tls 사용 안함

<details>
  <summary>templates/cr-secret.yaml 생성</summary>

``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: cr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {CR 토큰}
```

</details>

<details>
  <summary>values-custom.yaml 생성</summary>

``` yaml
# 내부 CR 사용하여 kong 설치
image:
  repository: {내부 registry & repo 경로}/kong
  tag: "3.5"
  pullPolicy: IfNotPresent
  pullSecrets:
  - cr-secret

# kong replica count
replicaCount: 3

# kong DB
env:
  prefix: /kong_prefix/
  database: postgres

# Ingress에서 src_ip를 X-Forwarded-For로 넘겨줌 → 이걸 실제 IP로 재설정
customEnv:
  KONG_TRUSTED_IPS: "0.0.0.0/0,::/0"
  KONG_REAL_IP_HEADER: X-Forwarded-For

# admin-api config
admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8001
  tls:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: "admin-api.test.io"

# kong-manager config
manager:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8002
  tls:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: "kong-manager.test.io"

# kong-proxy config
proxy:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
    servicePort: 80
    containerPort: 8000
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: "api-gw.test.io"

# DB config
postgresql:
  enabled: true
  auth:
    username: kong
    database: kong
  image:
    tag: latest

# not use kong ingress controller
ingressController:
  enabled: false
```

</details>

<details>
  <summary>charts/postgresql/values.yaml 수정</summary>

ArgoCD를 사용하면 하위 차트의 별도 values를 지정하기 어려운 것 같아 기본 values.yaml 파일을 수정하였습니다.
``` yaml
global:
  imagePullSecrets: 
  - cr-secret
  storageClass: "nfs-client"
image:
  registry: {내부 registry 경로}
  repository: {내부 repo 경로}/postgresql
```

</details>

설정이 완료되면 `helm install kong .` 명령어를 사용하여 설치하면 됩니다! 👍👍👍
