### ISSUE TITLE
K8S 환경에서 loki-stack 설치하기 🥕

### ISSUE THREAD

**Issue by jisunlim** [jisunlim/bibi-blog#19]
> https://artifacthub.io/packages/helm/grafana/loki-stack 2.9.11 version

거의 이틀을 꼬박 삽질한 Grafana - Loki - Fluent bit 설치 시작합니다ㅠ!!

쿠버네티스 환경에서 설치를 진행하였으며 Helm Chart를 사용하였습니다.
Loki, Loki-Stack, Loki-Distributed 등 여러가지 패키지가 있는데, 저는 그 중 Loki-Stack을 선택하였습니다.

처음에는 Read, Write 기능을 별도 모듈로 구성할 수 있는 Loki Scalable mode를 사용하려고 했는데요,
커스텀 설정이 어렵고 관련 문서도 찾기 어려워 Simple mode(Monolithic mode) 밖에 설치가 되지 않았습니다.

해당 모드를 사용할 바에는 거의 동일하지만 Fluent-bit 등을 함께 설치할 수 있는 Loki-Stack을 사용하기로 결정하였습니다.
Loki-Stack은 Scalable mode가 안되고 Simple mode 한가지만 지원하는 것 같더라구요 ㅎㅎ..ㅠㅠ
(모드 참고: https://grafana.com/docs/loki/latest/get-started/deployment-modes/)

Loki-Distributed 차트는 Loki로 Migrate되는 것을 보아 향후 지원 종료될 수 있을 것 같아 후보에서 제외하였습니다.
https://grafana.com/docs/loki/latest/setup/migrate/migrate-from-distributed/

# 1. 개요
## 1.1. Fluent Bit
컨테이너 로그를 수집하기 위해 설치하였습니다. Fluentd와 유사하나 더 경량화된 모델입니다.
https://docs.fluentbit.io/manual/

## 1.2. Loki
Elasticsearch와 같이 로그를 모아 검색/분석할 수 있는 도구입니다.
ES보다 가볍지만 풀 인덱싱을 하지 않아 검색 능력은 약간 부족합니다.
https://grafana.com/docs/loki/latest/

# 2. 설치
`helm upgrade --install loki grafana/loki-stack -f values-custom.yaml` 명령어로 설치 진행하였습니다.
시각화 도구로는 Grafana를 사용하였으나, Prometheus-Stack에서 이미 Grafana를 설치한 상태라 추가 설치하지 않았습니다.
필요하다면 Loki-Stack values.yaml 값 중 grafana.enabled=true 설정을 하여 설치 가능합니다.

## 2.1. loki + fluent-bit 통합 설치
단일 클러스터를 사용하거나, 멀티 클러스터 중 한 곳에 loki를 설치할 때 사용합니다.
``` yaml
test_pod:
  enabled: false

loki:
  enabled: true
  ingress:               # 하위 차트에 대한 values 값은 charts/loki/values.yaml 등에서 직접 확인하는게 좋습니다.
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: loki.test.com # host명 변경
        paths: 
          - /
  persistence:
    enabled: true
    storageClassName: nfs-client
    accessModes: ["ReadWriteOnce"]
    size: 10Gi

fluent-bit:
  enabled: true

promtail:
  enabled: false
```

## 2.2. fluent-bit 단독 설치
멀티 클러스터 환경 등에서 fluent-bit만 설치하고 loki로 전송할 때 사용합니다.
fluent-bit 공식 helm chart를 사용하려면 별도 커스터마이징이 필요하여, 이미 설정된 loki의 fluent-bit를 사용하였습니다.
(커스터마이징을 시도해봤는데 아직 경험이 부족해서 잘 안되더라구요ㅠㅠ)
``` yaml
test_pod:
  enabled: false

loki:
  enabled: false

fluent-bit:
  enabled: true
  loki:
    serviceName: "loki.test.com"  # loki ingress host 주소
    servicePort: 80

promtail:
  enabled: false
```

## 3. Grafana 설정
Grafana > Datasource > Loki 선택 후 서비스:포트 입력하여 설정하였습니다.
http://loki-stack.logging.svc.cluster.local:3100 (logging namespace)
![image](https://github.com/jisunlim/bibi-blog/assets/18459083/ab360ef8-6e87-4636-94c9-4e7c2364af2a)
