### ISSUE TITLE
K8S 환경에서 Grafana & Prometheus 설치하기

### ISSUE THREAD

**Issue by jisunlim** [jisunlim/bibi-blog#20]
> https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack 55.3.0 version

# 1. 개요
쿠버네티스 멀티 클러스터 환경에서 모니터링을 하기 위해 Prometheus를 설치하게 되었습니다.
Promethues로 모니터링 지표를 수집하고 Grafana로 시각화하여 보여주는 구성입니다.
한 클러스터에만 Grafana를 설치하고, 모든 클러스터에 Prometheus 설치하였습니다.

# 2. 설치
## Grafana 설치 + gitlab 연동
```  yaml
replicas: 1  # statefulset 타입에서는 2개 이상 하면 문제가 발생하는 것 같음 (too many redirect)

testFramework:
  enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana-dev.example.io
  tls:
    - secretName: secret-tls
      hosts:
        - grafana-dev.example.io

persistence:
  type: statefulset  # Helm Chart를 재설치하더라도 volume이 남아있었으면 해서 pvc 대신 statefulset 타입을 사용함
  enabled: true
  storageClassName: nfs-client

initChownData:
  enabled: false

grafana.ini:
  auth.gitlab:
    enabled: true
    allow_sign_up: true
    auto_login: false
    client_id:
    client_secret: 
    scopes: read_user openid email profile
    auth_url: https://gitlab-dev.example.io/oauth/authorize
    token_url: https://gitlab-dev.example.io/oauth/token
    api_url: https://gitlab-dev.example.io/api/v4
    role_attribute_path: contains(groups[*], 'main-group') && 'Admin' || 'Viewer'
    allow_assign_grafana_admin: false
    use_refresh_token: true
  server:
    root_url: https://grafana-dev.example.io/

assertNoLeakedSecrets: false
```
### Gitlab Application 설정
- callback url: https://grafana-dev.example.io/login/gitlab
- Trusted: No
- Confidential: Yes
- Scopes: api, read_api, read_user, openid, profile, email

### 트러블슈팅
grafana에서 gitlab 로그인 시 `The redirect URI included is not valid` 에러가 발생한다면 grafana.ini 설정 내 server.root_url 확인 (미설정시 해당 에러가 발생하였음)

----
## 2.1. Grafana + Prometheus 통합 설치
여러 클러스터 중 모니터링을 관리할 하나의 클러스터에만 설치하였습니다.
`helm upgrade --install prometheus-stack prometheus-community/prometheus-stack -f values-custom.yaml`
``` yaml
alertmanager:
  enabled: false
  alertmanagerSpec:
    image:
      repository: sec-plat-manage-cr/alertmanager

grafana:
  adminPassword: admin1234 # https://randomkeygen.com/에서 랜덤하게 생성하여 사용하였습니다.

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.test.com # host명 

  sidecar:
    datasources:
      defaultDatasourceEnabled: false
      isDefaultDatasource: false
      uid: manage-cluster
      alertmanager:
        enabled: false
```

## 2.2. Prometheus 단독 설치
나머지 모든 클러스터에 설치하였습니다.
`helm upgrade --install prometheus prometheus-community/prometheus -f values-custom.yaml`
``` yaml
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - prometheus-1.test.com # host명
  persistentVolume:
    storageClass: nfs-client

alertmanager:
  enabled: false
```

## 3. Grafana 설정
Grafana > Datasource > Prometheus 선택 후 서비스:포트 또는 host명을 입력하였습니다.
- 2.1 case: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
- 2.2 case: http://prometheus-1.tset.com

![image](https://github.com/jisunlim/bibi-blog/assets/18459083/1c0b4278-fbb3-46db-a2ed-06d0583d75f0)

## 4. Scrape 설정
metric을 수집할 pod annotation에 `prometheus.io/scrape="true"` 어노테이션 추가
![image](https://github.com/jisunlim/bibi-blog/assets/18459083/07dda14c-1d81-4835-86b2-7985c4c6b6e7)

prometheus에서 해당 pod이 존재하는 네임스페이스 등이 노출되는 것을 확인
(스크랩하지 않으면 관련 정보들이 나타나지 않음)
![image](https://github.com/jisunlim/bibi-blog/assets/18459083/c1f810c7-5d6a-436d-a64b-430e223ccbd9)
