### ISSUE TITLE
ArgoCD GitLab SSO 세팅하기

### ISSUE THREAD

**Issue by jisunlim** [jisunlim/bibi-blog#26]
매번 자료가 부족한건.. 제가 검색을 잘 못하는거겠죠? 자료가 없는건 아니죠? 🥲

[infracloud 블로그](https://www.infracloud.io/blogs/enabling-sso-authentication-argo-cd/)를 참고하여 무한 삽질끝에 성공했습니다..!!
Helm Chart는 argo/argo-cd 5.51.6 버전을 사용하였습니다.

설치 명령어는 아래와 같구요!
``` bash
# https://artifacthub.io/packages/helm/argo/argo-cd
helm repo add argo https://argoproj.github.io/argo-helm
helm install my-argo-cd argo/argo-cd --version 5.51.6 -f values-custom.yaml
```

삽질에 삽질을 거듭하던... 커스텀한 value 값입니다!!
``` yaml
server:
  extraArgs:
    - --insecure  # 아직 TLS 설정을 하지 않아서 insecure 세팅을 함
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
      - my-argocd.com
    ingressClassName: "nginx"  # ingress controller 사전 설치 필요

configs:
  cm:
    url: https://my-argocd.com
    dex.config: |
      connectors:
      - type: gitlab
        id: gitlab
        name: GitLab
        config:
          baseURL: http://my-gitlab.com
          redirectURI: https://my-argocd.com/api/dex/callback
          clientID: {ID}
          clientSecret: {Secret}
          scopes: ["read_user", openid", "profile", "email"]
  rbac:
    policy.default: 'role:user'
    policy.csv: |
      p, role:user, applicationsets, *, */*, allow
      p, role:user, applications, *, */*, allow
      p, role:user, repositories, *, *, allow
      p, role:user, logs, *, *, allow
      p, role:user, exec, *, *, allow

```

아래처럼 나오면 성공입니다!!! 🎉🎉🎉
![image](https://github.com/jisunlim/bibi-blog/assets/18459083/12298dcd-81a6-4bd7-8867-d9ff5aa2fb8d)

argocd 페이지에서 **LOG IN VIA GITLAB** 버튼을 클릭하면 gitlab 계정으로 로그인 가능합니다. :)
![image](https://github.com/jisunlim/bibi-blog/assets/18459083/92605f83-ae51-4659-a6c4-60327342e1d3)
