### ISSUE TITLE
kubernetes vue3 vite dockerize

### ISSUE THREAD

**Issue by jisunlim** [jisunlim/bibi-blog#35]
- vue-route: nginx.conf 재정의 필요
  - https://mherman.org/blog/dockerizing-a-vue-app/
- 환경변수
  - 빌드 후 js 파일에서 변경 필요
  - https://medium.com/@cgaspard/dynamically-configuring-vue-js-apps-in-docker-containers-0d2570c8f48c
  - https://stackoverflow.com/questions/59722631/passing-environment-variables-at-runtime-to-vue-js-application-with-docker-compo

[전체]
root/dockerize/nginx.conf
``` conf
server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }
}
```
root/dockerize/entrypoint.sh
``` shell
#!/bin/sh

ROOT_DIR=/usr/share/nginx/html

for file in "$ROOT_DIR"/assets/*.js;
do
  echo "Processing $file ..."
  sed -i "s|__API_URL__|${API_URL}|g" "$file"
done

nginx -g "daemon off;"
```
in source
``` ts
const http = axios.create({
    baseURL: import.meta.env.VITE_API_URL || "__API_URL__",
    headers: {'content-type': 'application/json'},
    withCredentials: true
})
```
root/Dockerfile
``` dockerfile
# Build
FROM node:20.11.1-alpine as build-stage
WORKDIR /app

COPY package.json .
RUN npm install

COPY . .
RUN npm run build

# Run Nginx
FROM nginx:1.24-alpine3.17 as production-stage
WORKDIR /usr/share/nginx/html
COPY --from=build-stage /app/dist .

RUN rm /etc/nginx/conf.d/default.conf
COPY dockerize/nginx.conf /etc/nginx/conf.d/

COPY dockerize/entrypoint.sh .
RUN chmod +x ./entrypoint.sh

EXPOSE 80
ENTRYPOINT ["./entrypoint.sh"]
```
deployment.yaml
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      spec:
        containers:
        - name: my-app
          image: my-app:latest
          env:
          - name: API_URL
             value: https://my-app.com
```
