### ISSUE TITLE
github & gitlab 미러링

### ISSUE THREAD

**Issue by jisunlim** [jisunlim/bibi-blog#36]
# 미러링 방법
## 1. github → gitlab
1. github actinos 사용
=> secret(TARGET_URL, TARGET_USERNAME, TARGET_TOKEN) 추가 후 아래 workflow 사용
=> 만일 보호 설정된 브랜치일 경우 해당 권한을 가진 계정만 사용 가능함 (Settings > Repository > Protected branches 확인)
```yaml
name: Sync Repository
 
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  push-to-gitlab:
    runs-on: [ self-hosted ]
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      
      - name: Set remote repository
        env:
          gitlab_url: ${{ secrets.TARGET_URL }}
          gitlab_username: ${{ secrets.TARGET_USERNAME }}
          gitlab_token: ${{ secrets.TARGET_TOKEN }}
        run: | # add gitlab repo if it isn't exist
          git config remote.gitlab.url >&- || git remote add gitlab https://${gitlab_username}:${gitlab_token}@${gitlab_url#https://};

      - name: Force push everthing
        run: | # main branch mirroring
          git push -f gitlab main 
```
2. gitlab pull mirroring 사용 => 상위 라이센스 필요

## 2. gitlab → github
gitlab push mirroring 사용
1. 빈 repo 생성
2. Settings > Repository 메뉴 접속
3. Mirroring repositories 클릭
4. Add new 버튼 클릭 후 github 정보 입력

# 트러블슈팅
Remote mirrors url is blocked: Requests to the local network are not allowed
1. 관리자 페이지 접속: ex. gitlab.com/admin
5. Settings > Network 메뉴 접속
6. Outbound requests 클릭
7. Allow requests to the local network from webhooks and integrations 활성화

# 참고
https://coding-groot.tistory.com/153
