### ISSUE TITLE
Pod Security Admission

### ISSUE THREAD

**Issue by jisunlim** [jisunlim/bibi-blog#47]
https://kubernetes.io/docs/concepts/security/pod-security-standards/

## 1. 내장 프로필
- Privileged: 대부분의 권한 허용
- Baseline: 최소한의 권한 제한
- Restricted: 엄격한 권한 제한

## 2. 모드
- enforce: pod 생성 요청 거부
![image](https://github.com/user-attachments/assets/6f18deb9-ad31-426c-b8ea-823b3bebda6a)
- audit: 감사 로깅
- warn: 경고 알림
![image](https://github.com/user-attachments/assets/4774a605-a95d-46b4-bf75-f15a9c943f93)

## 3. 사용 방법
네임스페이스에 label 설정
``` yaml
apiVersion: v1
kind: Namespace
metadata:
  name: restricted-ns
  labels:
    pod-security.kubernetes.io/enforce: restricted
```
